name: Publish Preview Release
on:
    pull_request:
        types: [ready_for_review, synchronize, opened, labeled]
        paths: [packages/**]

jobs:
    preview-release:
        if: github.repository == 'huntabyte/bits-ui' && contains(github.event.pull_request.labels.*.name, 'publish:preview')
        timeout-minutes: 5
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - name: install dependencies
              run: pnpm install --frozen-lockfile --prefer-offline

            - name: build
              run: pnpm build:packages

            - name: publish preview
              run: |
                  pnpx pkg-pr-new@0.0 publish --pnpm --compact './packages/*'
